version: "3.9"
services:
  traefik:
    container_name: traefik
    image: traefik
    labels:
      - traefik.enable=false
    command: --web --docker.domain.localhost --logLevel=DEBUG
    ports:
      - "9080:80"
      - "9880:8080"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock
