version: "3.9"

services:
  traefik:
    container_name: traefik
    image: traefik:v2.9
    labels:
      - traefik.enable=false
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs/:/logs/
