providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"
    exposedByDefault: false

api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: :80

log:
  level: "DEBUG"
  filePath: "./logs/traefik.log"

accessLog:
  filePath: "./logs/access.log"
  

